name: UI-KIT
on:
 push:
   branches:
    -main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - name: Print hello
       run: echo "Hello word buid"
      
  testing:     
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
     - name: Print hello
       run: echo "Hello word testing"
