name: UI-KIT
on:
 push:
   branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - name: Install
       uses: actions/checkout@v2.5.0
       
     - name: Setup node
       uses: actions/setup-node@v3
       with:
         node-version: latest
     - name: Install    
       run: yarn dev
      
  testing:     
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
     - name: Print hello
       run: echo "Hello word testing"
